### ISSUE TITLE
Questions about the RRC-power dataset

### ISSUE THREAD

**Issue by lgs96** [SIGCOMM21-5G/artifact#12]
Thank you for the great work and for sharing a meaningful dataset from your efforts.

I'm trying to model power consumption during the idle time of the DRX cycle and on-duration.
So I tried to use your data from  RRC-power, then I got two questions about the RRC-power datasets,

1. What is for mmWave dataset in trace 4-6 of the RRC-power dataset? (There is no label for mmWave 5G and low-band 5G)
2 How can I figure out the 4G-5G switch timing in trace 4-6 of the RRC-power dataset?

**Comment by Shawnxm** [comment]
Thanks for your questions.

1. The three traces whose titles contain "5g" were all collected under mmWave 5G. Also, I just uploaded the two missing 4G traces.
2. There are two peaks (higher than others) after UE promotes from the IDLE state. The duration between these two peaks is regarded as the 4G-5G switch time.

For example, if you use the following command to plot a trace and zoom in to Time=87-103s, you will find the two peaks at 89.600s and 91.206s.
```
python plot_hardware_power.py [path-to-dataset]/RRC-Power/PowerMonitor/screenmax-5g-loop1-rrc-1.csv' 5
```

**Comment by lgs96** [comment]
Thank you for the perfect answer. My questions are solved.
