### ISSUE TITLE
Is it possible to share the dash video?

### ISSUE THREAD

**Issue by godka** [SIGCOMM21-5G/artifact#13]
I downloaded the video from Youtube. However, the maximum bitrate didn't reach 40mbps.
So is it possible to share the dash video to me for research only?

Thx!

**Comment by ry4nzhu** [comment]
Sorry for the late reply. Yes the original video does not reach 40mbps bitrate. We use ffmpeg to produce dash segments with higher bitrates. I've made the dash video available [here](https://drive.google.com/drive/folders/1_Hxz6M8qxZJnpJz38ll-Bw7OV1U4FDSk?usp=sharing). Besides, I attached the scripts for preparing dash video (`prepare-dash-video.py`) in the same drive directory. Hope that helps!

Thanks.
