### ISSUE TITLE
Choosing chunk length in throughput prediction experiments + html files for chunk length experiment

### ISSUE THREAD

**Issue by may3141** [SIGCOMM21-5G/artifact#14]
I want to run the throughput prediction experiment for 4s chunk length. However, the chunk length experiment does not have the provision for prediction traces like in throughput prediction experiment. Is it possible to set a particular chunk length for throughput prediction experiments?
Additionally, please let me know how I can find the html files for chunk length experiments.

**Comment by ry4nzhu** [comment]
As stated in the README, the throughput prediction traces are in the format of predicted throughput for each second, so you can directly use them for variable chunk length experiments (just be careful about the time and the predicted throughput around/at that particular timestamp).  

For the html files, you can refer to this [sample](https://github.com/hongzimao/pensieve/blob/master/video_server/myindex_fastMPC.html). Assuming you have generated a manifest file for 4s chunks DASH video, you can just provide that manifest in the html to start the experiments.
