### ISSUE TITLE
How can these bash scripts run successfully?

### ISSUE THREAD

**Issue by n13eho** [SIGCOMM21-5G/artifact#16]
hello, i'm a starter trying to run the `ABR-5G/run_exp/run_5g_driving.sh` and failed constantly, i have questions below:
 1. the `server_ip=172.31.51.127` in the file `run_5g_driving.sh` doesn't seem reasonable, for the abr server are actually started at localhost, so this seem quit weird. I replaced it with `127.0.0.1`
 2. the script `run_video.py` is meant to start the local abr server, and make a selenium move to request for the content by the url, but i try serveral times only to find the `get(url)` is only a `GET` method, while all the abr logic is written in the `POST` method, as it stated in `ABR-5G/rl_server/robust_mpc_server.py` and all other server scripts.
 3. the url client ask for is `http://' + ip + '/' + 'myindex_' + abr_algo + '.html`, but there's no html file under `rl_server/`, i tried to move pensieve's `myindex_robustMPC.html` to there but that just made no difference for the real promble lies in the code of `abr_server.py` where i don't have a clue
 So i wonder **how these scripts can actually work**? Did i miss something here?

**Comment by ry4nzhu** [comment]
- The server ip in the script is used when the ABR server is set up using a virtual machine. It'd better if you can setup a VM and host the video content there.
- Only MPC and RL algorithm compute the ABR logic in `{algorithm}_server.py`, the other ABR logic resides in the dash.js framework (abrController.js).
- For your third question, yes you can adopt pensieve's `myindex_{algorithm}.html`, but you will need to prepare your own video and change the manifest file in order for it to work.

**Comment by ry4nzhu** [comment]
FYI, https://github.com/SIGCOMM21-5G/artifact/issues/13#issuecomment-1159836221 has the link to the DASH video we used. You can set it up using the video if you'd want.

**Comment by n13eho** [comment]
谢谢！我再试试
